import { z } from "zod";
const warnings = z.object({
  warning: z.string(),
  severity: z.number(),
});
export const calorieResponseSchema = z.object({
  description: z.string(),
  calories: z.number(),
  quantity: z.string(),
  warnings: z.array(warnings),
  isProcessedFood: z.boolean(),
  glycemicIndex: z.number(),
  vegetableServings: z.number(),
  fruitServings: z.number(),
  nutrients: z.object({
    carbohydrates: z.number(),
    proteins: z.number(),
    fats: z.number(),
    fiber: z.number(),
    sodium: z.number(),
    naturalSugar: z.number(),
    addedSugar: z.number(),
    calcium: z.number(),
    magnesium: z.number(),
    iron: z.number(),
    potassium: z.number(),
    omega_3: z.number(),
    cholesterol: z.number(),
    zinc: z.number(),
    vitaminD: z.number(),
    vitaminB12: z.number(),
    vitaminC: z.number(),
    vitaminE: z.number(),
  }),
});

export const calorieResponseArraySchema = z.object({
  meals: z.array(calorieResponseSchema),
  mealName: z.string(),
  mealType: z.string(),
});
enum UnitMeasure {
  GRAM = "g",
  MILLIGRAM = "mg",
  WHOLE = "whole",
  OUNCE = "oz",
  POUND = "lb",
  CUP = "cup",
  SERVING = "serving",
  SLICE = "slice",
  TABLESPOON = "tbsp",
  TEASPOON = "tsp",
}

export const calorieResponseTool = {
  type: "function" as const,
  function: {
    name: "generateCalorieResponse",
    description: "Generates calorie and nutritional information for meals",
    parameters: {
      type: "object",
      properties: {
        meals: {
          type: "array",
          items: {
            type: "object",
            properties: {
              description: { type: "string" },
              calories: { type: "number" },
              quantity: { type: "string" },
              measurementUnit: {
                type: "string",
                enum: Object.values(UnitMeasure),
              },
              warnings: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    warning: { type: "string" },
                    severity: { type: "number" },
                  },
                  required: ["warning", "severity"],
                },
              },
              isProcessedFood: { type: "boolean" },
              glycemicIndex: { type: "number" },
              vegetableServings: { type: "number" },
              fruitServings: { type: "number" },
              nutrients: {
                type: "object",
                properties: {
                  carbohydrates: { type: "number" },
                  proteins: { type: "number" },
                  fats: { type: "number" },
                  fiber: { type: "number" },
                  sodium: { type: "number" },
                  naturalSugar: { type: "number" },
                  addedSugar: { type: "number" },
                  calcium: { type: "number" },
                  magnesium: { type: "number" },
                  iron: { type: "number" },
                  potassium: { type: "number" },
                  omega_3: { type: "number" },
                  cholesterol: { type: "number" },
                  zinc: { type: "number" },
                  vitaminD: { type: "number" },
                  vitaminB12: { type: "number" },
                  vitaminC: { type: "number" },
                  vitaminE: { type: "number" },
                },
                required: [
                  "carbohydrates",
                  "proteins",
                  "fats",
                  "fiber",
                  "sodium",
                  "naturalSugar",
                  "addedSugar",
                  "calcium",
                  "magnesium",
                  "iron",
                  "potassium",
                  "omega_3",
                  "cholesterol",
                  "zinc",
                  "vitaminD",
                  "vitaminB12",
                  "vitaminC",
                  "vitaminE",
                ],
              },
            },
            required: [
              "description",
              "calories",
              "quantity",
              "measurementUnit",
              "warnings",
              "isProcessedFood",
              "glycemicIndex",
              "vegetableServings",
              "fruitServings",
              "nutrients",
            ],
          },
        },
        mealName: { type: "string" },
        mealType: { type: "string" },
      },
      required: ["meals", "mealName", "mealType"],
    },
  },
};
export const caloriesArrayResponseTool = {
  type: "function" as const,
  function: {
    name: "generateCalorieResponse",
    description: "Generates calorie and nutritional information for meals",
    parameters: {
      type: "object",
      properties: {
        meals: {
          type: "array",
          items: {
            type: "object",
            properties: {
              ingredients: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: { type: "string" },
                    calories: { type: "number" },
                    quantity: { type: "string" },
                    measurementUnit: {
                      type: "string",
                      enum: Object.values(UnitMeasure),
                    },
                    warnings: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          warning: { type: "string" },
                          severity: { type: "number" },
                        },
                        required: ["warning", "severity"],
                      },
                    },
                    isProcessedFood: { type: "boolean" },
                    glycemicIndex: { type: "number" },
                    vegetableServings: { type: "number" },
                    fruitServings: { type: "number" },
                    nutrients: {
                      type: "object",
                      properties: {
                        carbohydrates: { type: "number" },
                        proteins: { type: "number" },
                        fats: { type: "number" },
                        fiber: { type: "number" },
                        sodium: { type: "number" },
                        naturalSugar: { type: "number" },
                        addedSugar: { type: "number" },
                        calcium: { type: "number" },
                        magnesium: { type: "number" },
                        iron: { type: "number" },
                        potassium: { type: "number" },
                        omega_3: { type: "number" },
                        cholesterol: { type: "number" },
                        zinc: { type: "number" },
                        vitaminD: { type: "number" },
                        vitaminB12: { type: "number" },
                        vitaminC: { type: "number" },
                        vitaminE: { type: "number" },
                      },
                      required: [
                        "carbohydrates",
                        "proteins",
                        "fats",
                        "fiber",
                        "sodium",
                        "naturalSugar",
                        "addedSugar",
                        "calcium",
                        "magnesium",
                        "iron",
                        "potassium",
                        "omega_3",
                        "cholesterol",
                        "zinc",
                        "vitaminD",
                        "vitaminB12",
                        "vitaminC",
                        "vitaminE",
                      ],
                    },
                  },
                  required: [
                    "description",
                    "calories",
                    "quantity",
                    "measurementUnit",
                    "warnings",
                    "isProcessedFood",
                    "glycemicIndex",
                    "vegetableServings",
                    "fruitServings",
                    "nutrients",
                  ],
                },
              },
              mealName: { type: "string" },
              mealType: { type: "string" },
              mealDate: { type: "string" },
            },
            required: ["ingredients", "mealName", "mealType"],
          },
        },
        dateReference: { type: "string" },
        dateConfidence: { type: "number" },
      },
      required: ["meals"],
    },
  },
};

export const LabCategoryEnum = z.enum([
  "Liver",
  "Kidney",
  "Lipid panel",
  "Glucose",
  "Thyroid",
  "Hematology",
  "Iron",
  "Pancreas",
  "Cardiac Marker",
  "Urinalysis",
  "Vitamins",
  "Electrolytes",
  "Calcium",
  "Protein",
  "Inflammatory Markers",
  "Coagulation",
  "Metabolic Panel",
  "Hormones",
  "Enzymes",
  "Blood gases",
  "Infection Markers",
  "Bone Profile",
  "Toxicology",
  "Autoimmune",
  "Others",
]);

export const LabDataSchema = z.object({
  labResults: z.array(
    z.object({
      testType: z.string(),
      category: LabCategoryEnum,
      result: z.string(),
      referenceRange: z.string(),
      isOutOfRange: z.boolean(),
      units: z.string(),
      aboutTestType: z.string(),
    })
  ),
  labReport: z.string(),
  recommendations: z.object({
    nutrition: z.string(),
    exercise: z.string(),
  }),
});

export const labDataResponseTool = {
  type: "function" as const,
  function: {
    name: "generateLabDataResponse",
    description: "Generates structured lab data analysis with recommendations",
    parameters: {
      type: "object",
      properties: {
        labResults: {
          type: "array",
          items: {
            type: "object",
            properties: {
              testType: { type: "string" },
              category: {
                type: "string",
                enum: [
                  "Liver",
                  "Kidney",
                  "Lipid panel",
                  "Glucose",
                  "Thyroid",
                  "Hematology",
                  "Iron",
                  "Pancreas",
                  "Cardiac Marker",
                  "Urinalysis",
                  "Vitamins",
                  "Electrolytes",
                  "Calcium",
                  "Protein",
                  "Inflammatory Markers",
                  "Coagulation",
                  "Metabolic Panel",
                  "Hormones",
                  "Enzymes",
                  "Blood gases",
                  "Infection Markers",
                  "Bone Profile",
                  "Toxicology",
                  "Autoimmune",
                  "Others",
                ],
              },
              result: { type: "string" },
              referenceRange: { type: "string" },
              isOutOfRange: { type: "boolean" },
              units: { type: "string" },
              aboutTestType: { type: "string" },
            },
            required: [
              "testType",
              "category",
              "result",
              "referenceRange",
              "isOutOfRange",
              "units",
              "aboutTestType",
            ],
          },
        },
        labReport: { type: "string" },
        recommendations: {
          type: "object",
          properties: {
            nutrition: { type: "string" },
            exercise: { type: "string" },
          },
          required: ["nutrition", "exercise"],
        },
      },
      required: ["labResults", "labReport", "recommendations"],
    },
  },
};

export const parsedLabSchema = z.object({
  parsedLabs: z.array(
    z.object({
      resultName: z.string(),
      result: z.string(),
      referenceRange: z.string(),
    })
  ),
});
