import { z } from "zod";

// Meal Plan Schema
export const mealPlanSchema = z.object({
  days: z.array(
    z.object({
      day: z.string(),
      meals: z.object({
        breakfast: z.object({
          meal_description: z.string(),
          ingredients: z.array(z.string()),
          calories: z.number(),
          nutrients: z.object({
            carbohydrates: z.number(),
            proteins: z.number(),
            fats: z.number(),
            fiber: z.number(),
            sodium: z.number(),
            naturalSugar: z.number(),
            addedSugar: z.number(),
            calcium: z.number(),
            magnesium: z.number(),
            iron: z.number(),
            potassium: z.number(),
            omega_3: z.number(),
            cholesterol: z.number(),
            zinc: z.number(),
            vitaminD: z.number(),
            vitaminB12: z.number(),
            vitaminC: z.number(),
            vitaminE: z.number(),
          }),
        }),
        lunch: z.object({
          meal_description: z.string(),
          ingredients: z.array(z.string()),
          calories: z.number(),
          nutrients: z.object({
            carbohydrates: z.number(),
            proteins: z.number(),
            fats: z.number(),
            fiber: z.number(),
            sodium: z.number(),
            naturalSugar: z.number(),
            addedSugar: z.number(),
            calcium: z.number(),
            magnesium: z.number(),
            iron: z.number(),
            potassium: z.number(),
            omega_3: z.number(),
            cholesterol: z.number(),
            zinc: z.number(),
            vitaminD: z.number(),
            vitaminB12: z.number(),
            vitaminC: z.number(),
            vitaminE: z.number(),
          }),
        }),
        snack: z.object({
          meal_description: z.string(),
          ingredients: z.array(z.string()),
          calories: z.number(),
          nutrients: z.object({
            carbohydrates: z.number(),
            proteins: z.number(),
            fats: z.number(),
            fiber: z.number(),
            sodium: z.number(),
            naturalSugar: z.number(),
            addedSugar: z.number(),
            calcium: z.number(),
            magnesium: z.number(),
            iron: z.number(),
            potassium: z.number(),
            omega_3: z.number(),
            cholesterol: z.number(),
            zinc: z.number(),
            vitaminD: z.number(),
            vitaminB12: z.number(),
            vitaminC: z.number(),
            vitaminE: z.number(),
          }),
        }),
        dinner: z.object({
          meal_description: z.string(),
          ingredients: z.array(z.string()),
          calories: z.number(),
          nutrients: z.object({
            carbohydrates: z.number(),
            proteins: z.number(),
            fats: z.number(),
            fiber: z.number(),
            sodium: z.number(),
            naturalSugar: z.number(),
            addedSugar: z.number(),
            calcium: z.number(),
            magnesium: z.number(),
            iron: z.number(),
            potassium: z.number(),
            omega_3: z.number(),
            cholesterol: z.number(),
            zinc: z.number(),
            vitaminD: z.number(),
            vitaminB12: z.number(),
            vitaminC: z.number(),
            vitaminE: z.number(),
          }),
        }),
      }),
    })
  ),
  totalCalories: z.number(),
  dietType: z.string(),
  plan_description: z.string(),
});

