import { z } from "zod";

export const portionResponseTool = {
  type: "function" as const,
  function: {
    name: "generatePortions",
    description:
      "Generates portion sizes and nutritional information for ingredients",
    parameters: {
      type: "object",
      properties: {
        ingredients: {
          type: "array",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
              amount: { type: "number" },
              unit: {
                type: "string",
                enum: ["g", "oz", "pound"],
              },
              calories: { type: "number" },
              isProcessedFood: { type: "boolean" },
              vegetableServings: { type: "number" },
              glycemicIndex: { type: "number" },
              fruitServings: { type: "number" },
              nutrients: {
                type: "object",
                properties: {
                  carbohydrates: { type: "number" },
                  proteins: { type: "number" },
                  fats: { type: "number" },
                  fiber: { type: "number" },
                  sodium: { type: "number" },
                  naturalSugar: { type: "number" },
                  addedSugar: { type: "number" },
                  calcium: { type: "number" },
                  magnesium: { type: "number" },
                  iron: { type: "number" },
                  potassium: { type: "number" },
                  omega_3: { type: "number" },
                  cholesterol: { type: "number" },
                  zinc: { type: "number" },
                  vitaminD: { type: "number", description: "micrograms (µg)" },
                  vitaminB12: { type: "number", description: "micrograms (µg)" },
                  vitaminC: { type: "number", description: "milligrams (mg)" },
                  vitaminE: { type: "number", description: "milligrams (mg)" },
                },
                required: [
                  "carbohydrates",
                  "proteins",
                  "fats",
                  "fiber",
                  "sodium",
                  "naturalSugar",
                  "addedSugar",
                  "calcium",
                  "magnesium",
                  "iron",
                  "potassium",
                  "omega_3",
                  "cholesterol",
                  "zinc",
                  "vitaminD",
                  "vitaminB12",
                  "vitaminC",
                  "vitaminE",
                ],
              },
            },
            required: [
              "name",
              "amount",
              "unit",
              "calories",
              "isProcessedFood",
              "vegetableServings",
              "glycemicIndex",
              "fruitServings",
              "nutrients",
            ],
          },
        },
        mealName: { type: "string" },
      },
      required: ["ingredients", "mealName"],
    },
  },
};

export const nutritionCalcuationSchema = z.object({
  Explanation: z.string(),
  carbQuota: z.number(),
  proteinsQuota: z.number(),
  fatsQuota: z.number(),
});

export const caloricDeficitSchema = z.object({
  caloricDeficit: z.number(),
});
export const nutrientLimitSchema = z.object({
  explanation: z.string(),
  caloricAmount: z.number(),
  carbohydratesLimit: z.number(),
  proteinsLimit: z.number(),
  fatsLimit: z.number(),
  fiberLimit: z.number(),
  sodiumLimit: z.number(),
  naturalSugarLimit: z.number(),
  addedSugarLimit: z.number(),
  calciumLimit: z.number(),
  magnesiumLimit: z.number(),
  ironLimit: z.number(),
  potassiumLimit: z.number(),
  omega_3Limit: z.number(),
  cholesterolLimit: z.number(),
  zincLimit: z.number(),
  vitaminDLimit: z.number(),
  vitaminCLimit: z.number(),
  vitaminB12Limit: z.number(),
  vitaminELimit: z.number(),
});

export const nutrientLimitTool = {
  type: "function" as const,
  function: {
    name: "generateNutrientLimits",
    description: "Generates daily nutrient intake limits and recommendations",
    parameters: {
      type: "object",
      properties: {
        explanation: { type: "string" },
        caloricAmount: { type: "number" },
        carbohydratesLimit: { type: "number" },
        proteinsLimit: { type: "number" },
        fatsLimit: { type: "number" },
        fiberLimit: { type: "number" },
        sodiumLimit: { type: "number" },
        naturalSugarLimit: { type: "number" },
        addedSugarLimit: { type: "number" },
        calciumLimit: { type: "number" },
        magnesiumLimit: { type: "number" },
        ironLimit: { type: "number" },
        potassiumLimit: { type: "number" },
        omega_3Limit: { type: "number" },
        cholesterolLimit: { type: "number" },
        zincLimit: { type: "number" },
        vitaminDLimit: { type: "number", description: "micrograms (µg) per day" },
        vitaminCLimit: { type: "number" },
        vitaminB12Limit: { type: "number", description: "micrograms (µg) per day" },
        vitaminELimit: { type: "number" },
      },
      required: [
        "explanation",
        "caloricAmount",
        "carbohydratesLimit",
        "proteinsLimit",
        "fatsLimit",
        "fiberLimit",
        "sodiumLimit",
        "naturalSugarLimit",
        "addedSugarLimit",
        "calciumLimit",
        "magnesiumLimit",
        "ironLimit",
        "potassiumLimit",
        "omega_3Limit",
        "cholesterolLimit",
        "zincLimit",
        "vitaminDLimit",
        "vitaminCLimit",
        "vitaminB12Limit",
        "vitaminELimit",
      ],
    },
  },
};
