import { z } from "zod";

export const mealsResponseTool = {
  type: "function" as const,
  function: {
    name: "generateMealPlan",
    descritpion: "Generates a personalized meal plan",
    parameters: {
      type: "object",
      properties: {
        meals: {
          type: "array",
          items: {
            type: "object",
            properties: {
              description: { type: "string" },
              calories: { type: "number" },
              ingredients: { type: "string" },
            },
            required: ["description", "calories", "ingredients"],
          },
        },
      },
      required: ["meals"],
    },
  },
};
export const portionResponseTool = {
  type: "function" as const,
  function: {
    name: "generatePortions",
    description:
      "Generates portion sizes and nutritional information for ingredients",
    parameters: {
      type: "object",
      properties: {
        ingredients: {
          type: "array",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
              amount: { type: "number" },
              unit: {
                type: "string",
                enum: ["g", "oz", "pound"],
              },
              calories: { type: "number" },
              isProcessedFood: { type: "boolean" },
              vegetableServings: { type: "number" },
              glycemicIndex: { type: "number" },
              fruitServings: { type: "number" },
              nutrients: {
                type: "object",
                properties: {
                  carbohydrates: { type: "number" },
                  proteins: { type: "number" },
                  fats: { type: "number" },
                  fiber: { type: "number" },
                  sodium: { type: "number" },
                  naturalSugar: { type: "number" },
                  addedSugar: { type: "number" },
                  calcium: { type: "number" },
                  magnesium: { type: "number" },
                  iron: { type: "number" },
                  potassium: { type: "number" },
                  omega_3: { type: "number" },
                  cholesterol: { type: "number" },
                  zinc: { type: "number" },
                  vitaminD: { type: "number" },
                  vitaminB12: { type: "number" },
                  vitaminC: { type: "number" },
                  vitaminE: { type: "number" },
                },
                required: [
                  "carbohydrates",
                  "proteins",
                  "fats",
                  "fiber",
                  "sodium",
                  "naturalSugar",
                  "addedSugar",
                  "calcium",
                  "magnesium",
                  "iron",
                  "potassium",
                  "omega_3",
                  "cholesterol",
                  "zinc",
                  "vitaminD",
                  "vitaminB12",
                  "vitaminC",
                  "vitaminE",
                ],
              },
            },
            required: [
              "name",
              "amount",
              "unit",
              "calories",
              "isProcessedFood",
              "vegetableServings",
              "glycemicIndex",
              "fruitServings",
              "nutrients",
            ],
          },
        },
        mealName: { type: "string" },
      },
      required: ["ingredients", "mealName"],
    },
  },
};

export const nutritionCalcuationSchema = z.object({
  Explanation: z.string(),
  carbQuota: z.number(),
  proteinsQuota: z.number(),
  fatsQuota: z.number(),
});

export const caloricDeficitSchema = z.object({
  caloricDeficit: z.number(),
});
export const nutrientLimitSchema = z.object({
  explanation: z.string(),
  caloricAmount: z.number(),
  carbohydratesLimit: z.number(),
  proteinsLimit: z.number(),
  fatsLimit: z.number(),
  fiberLimit: z.number(),
  sodiumLimit: z.number(),
  naturalSugarLimit: z.number(),
  addedSugarLimit: z.number(),
  calciumLimit: z.number(),
  magnesiumLimit: z.number(),
  ironLimit: z.number(),
  potassiumLimit: z.number(),
  omega_3Limit: z.number(),
  cholesterolLimit: z.number(),
  zincLimit: z.number(),
  vitaminDLimit: z.number(),
  vitaminCLimit: z.number(),
  vitaminB12Limit: z.number(),
  vitaminELimit: z.number(),
});

export const nutrientLimitTool = {
  type: "function" as const,
  function: {
    name: "generateNutrientLimits",
    description: "Generates daily nutrient intake limits and recommendations",
    parameters: {
      type: "object",
      properties: {
        explanation: { type: "string" },
        caloricAmount: { type: "number" },
        carbohydratesLimit: { type: "number" },
        proteinsLimit: { type: "number" },
        fatsLimit: { type: "number" },
        fiberLimit: { type: "number" },
        sodiumLimit: { type: "number" },
        naturalSugarLimit: { type: "number" },
        addedSugarLimit: { type: "number" },
        calciumLimit: { type: "number" },
        magnesiumLimit: { type: "number" },
        ironLimit: { type: "number" },
        potassiumLimit: { type: "number" },
        omega_3Limit: { type: "number" },
        cholesterolLimit: { type: "number" },
        zincLimit: { type: "number" },
        vitaminDLimit: { type: "number" },
        vitaminCLimit: { type: "number" },
        vitaminB12Limit: { type: "number" },
        vitaminELimit: { type: "number" },
      },
      required: [
        "explanation",
        "caloricAmount",
        "carbohydratesLimit",
        "proteinsLimit",
        "fatsLimit",
        "fiberLimit",
        "sodiumLimit",
        "naturalSugarLimit",
        "addedSugarLimit",
        "calciumLimit",
        "magnesiumLimit",
        "ironLimit",
        "potassiumLimit",
        "omega_3Limit",
        "cholesterolLimit",
        "zincLimit",
        "vitaminDLimit",
        "vitaminCLimit",
        "vitaminB12Limit",
        "vitaminELimit",
      ],
    },
  },
};

export const mealPlanTool = {
  type: "function" as const,
  function: {
    name: "generateMealPlan",
    description:
      "Generates a comprehensive meal plan with daily meals and nutritional information",
    parameters: {
      type: "object",
      properties: {
        days: {
          type: "array",
          items: {
            type: "object",
            properties: {
              day: { type: "string" },
              meals: {
                type: "object",
                properties: {
                  breakfast: {
                    type: "object",
                    properties: {
                      meal_description: { type: "string" },
                      ingredients: {
                        type: "array",
                        items: { type: "string" },
                      },
                      calories: { type: "number" },
                      nutrients: {
                        type: "object",
                        properties: {
                          carbohydrates: { type: "number" },
                          proteins: { type: "number" },
                          fats: { type: "number" },
                          fiber: { type: "number" },
                          sodium: { type: "number" },
                          naturalSugar: { type: "number" },
                          addedSugar: { type: "number" },
                          calcium: { type: "number" },
                          magnesium: { type: "number" },
                          iron: { type: "number" },
                          potassium: { type: "number" },
                          omega_3: { type: "number" },
                          cholesterol: { type: "number" },
                          zinc: { type: "number" },
                          vitaminD: { type: "number" },
                          vitaminB12: { type: "number" },
                          vitaminC: { type: "number" },
                          vitaminE: { type: "number" },
                        },
                        required: [
                          "carbohydrates",
                          "proteins",
                          "fats",
                          "fiber",
                          "sodium",
                          "naturalSugar",
                          "addedSugar",
                          "calcium",
                          "magnesium",
                          "iron",
                          "potassium",
                          "omega_3",
                          "cholesterol",
                          "zinc",
                          "vitaminD",
                          "vitaminB12",
                          "vitaminC",
                          "vitaminE",
                        ],
                      },
                    },
                    required: [
                      "meal_description",
                      "ingredients",
                      "calories",
                      "nutrients",
                    ],
                  },
                  lunch: {
                    type: "object",
                    properties: {
                      meal_description: { type: "string" },
                      ingredients: {
                        type: "array",
                        items: { type: "string" },
                      },
                      calories: { type: "number" },
                      nutrients: {
                        type: "object",
                        properties: {
                          carbohydrates: { type: "number" },
                          proteins: { type: "number" },
                          fats: { type: "number" },
                          fiber: { type: "number" },
                          sodium: { type: "number" },
                          naturalSugar: { type: "number" },
                          addedSugar: { type: "number" },
                          calcium: { type: "number" },
                          magnesium: { type: "number" },
                          iron: { type: "number" },
                          potassium: { type: "number" },
                          omega_3: { type: "number" },
                          cholesterol: { type: "number" },
                          zinc: { type: "number" },
                          vitaminD: { type: "number" },
                          vitaminB12: { type: "number" },
                          vitaminC: { type: "number" },
                          vitaminE: { type: "number" },
                        },
                        required: [
                          "carbohydrates",
                          "proteins",
                          "fats",
                          "fiber",
                          "sodium",
                          "naturalSugar",
                          "addedSugar",
                          "calcium",
                          "magnesium",
                          "iron",
                          "potassium",
                          "omega_3",
                          "cholesterol",
                          "zinc",
                          "vitaminD",
                          "vitaminB12",
                          "vitaminC",
                          "vitaminE",
                        ],
                      },
                    },
                    required: [
                      "meal_description",
                      "ingredients",
                      "calories",
                      "nutrients",
                    ],
                  },
                  snack: {
                    type: "object",
                    properties: {
                      meal_description: { type: "string" },
                      ingredients: {
                        type: "array",
                        items: { type: "string" },
                      },
                      calories: { type: "number" },
                      nutrients: {
                        type: "object",
                        properties: {
                          carbohydrates: { type: "number" },
                          proteins: { type: "number" },
                          fats: { type: "number" },
                          fiber: { type: "number" },
                          sodium: { type: "number" },
                          naturalSugar: { type: "number" },
                          addedSugar: { type: "number" },
                          calcium: { type: "number" },
                          magnesium: { type: "number" },
                          iron: { type: "number" },
                          potassium: { type: "number" },
                          omega_3: { type: "number" },
                          cholesterol: { type: "number" },
                          zinc: { type: "number" },
                          vitaminD: { type: "number" },
                          vitaminB12: { type: "number" },
                          vitaminC: { type: "number" },
                          vitaminE: { type: "number" },
                        },
                        required: [
                          "carbohydrates",
                          "proteins",
                          "fats",
                          "fiber",
                          "sodium",
                          "naturalSugar",
                          "addedSugar",
                          "calcium",
                          "magnesium",
                          "iron",
                          "potassium",
                          "omega_3",
                          "cholesterol",
                          "zinc",
                          "vitaminD",
                          "vitaminB12",
                          "vitaminC",
                          "vitaminE",
                        ],
                      },
                    },
                    required: [
                      "meal_description",
                      "ingredients",
                      "calories",
                      "nutrients",
                    ],
                  },
                  dinner: {
                    type: "object",
                    properties: {
                      meal_description: { type: "string" },
                      ingredients: {
                        type: "array",
                        items: { type: "string" },
                      },
                      calories: { type: "number" },
                      nutrients: {
                        type: "object",
                        properties: {
                          carbohydrates: { type: "number" },
                          proteins: { type: "number" },
                          fats: { type: "number" },
                          fiber: { type: "number" },
                          sodium: { type: "number" },
                          naturalSugar: { type: "number" },
                          addedSugar: { type: "number" },
                          calcium: { type: "number" },
                          magnesium: { type: "number" },
                          iron: { type: "number" },
                          potassium: { type: "number" },
                          omega_3: { type: "number" },
                          cholesterol: { type: "number" },
                          zinc: { type: "number" },
                          vitaminD: { type: "number" },
                          vitaminB12: { type: "number" },
                          vitaminC: { type: "number" },
                          vitaminE: { type: "number" },
                        },
                        required: [
                          "carbohydrates",
                          "proteins",
                          "fats",
                          "fiber",
                          "sodium",
                          "naturalSugar",
                          "addedSugar",
                          "calcium",
                          "magnesium",
                          "iron",
                          "potassium",
                          "omega_3",
                          "cholesterol",
                          "zinc",
                          "vitaminD",
                          "vitaminB12",
                          "vitaminC",
                          "vitaminE",
                        ],
                      },
                    },
                    required: [
                      "meal_description",
                      "ingredients",
                      "calories",
                      "nutrients",
                    ],
                  },
                },
                required: ["breakfast", "lunch", "snack", "dinner"],
              },
            },
            required: ["day", "meals"],
          },
        },
        totalCalories: { type: "number" },
        dietType: { type: "string" },
        plan_description: { type: "string" },
      },
      required: ["days", "totalCalories", "dietType", "plan_description"],
    },
  },
};
